### ISSUE TITLE
Docker container always restarts

### ISSUE THREAD

**Issue by MGoeppl** [cooperspencer/gickup#33]
My container is set to restart: always. 

It always restarts, I think it may be the case that the image is not using a loop, but rather completed the execution and stops the container, thus triggering a restart by the docker daemon.

Is this behaviour intended?

The easiest solution probably would be to write a file that triggers the main.go every 15 minutes or so, and using this one as the main Docker image executable.

**Comment by cooperspencer** [comment]
Hi,
I haven't implemented a servermode/long running mode for now. It just runs once and exits after it is done, which means your container restarts because of that behavior. For now I would suggest to just run the container from a cronjob.
I will implement a cron-mode in gickup in the next few days and then the container will run as you would expect it.

**Comment by colindean** [comment]
Awesome! I was about to patch together a solution using [docker-cron](https://github.com/cshtdd/docker-cron) but having some kind of scheduling thing baked in would be simpler at least for me the consumer of the Docker container!

**Comment by cooperspencer** [comment]
If you add the cron option in the config file, it should run without the constant restarts.

**Comment by cooperspencer** [comment]
just tested it with the container and it seems to work for me
